spring:
    data:
        mongodb:
        host: ds029486.mlab.com
        port: 37101
        database: usuarios
        username: ahorcado
        password: ahorcado
    redis:
        host: 192.168.56.101
        port: 6379
        #password:
